"""Regenerate the two larger SWMM kinematic-wave parity fixtures (run from the repo root).

`example1_kinwave.inp` -- the conduit network of EPA SWMM 5's published `Example1.inp`
(USEPA/swmm-nrtestsuite `public/examples/Example1.inp`): its 13 junctions, outfall, 13
CIRCULAR conduits and cross-sections, with every length, elevation, offset and diameter
converted from feet to metres (x 0.3048, so SWMM's internal feet recover the published
numbers). The sewer application models neither runoff nor CFS units, so the eight
subcatchments, the rain gauge and its time series are replaced by constant inflows at the
subcatchment outlet nodes from the rational method ``Q = C i A`` with ``C = %Imperv / 100``
and ``i = 0.25 in/hr`` (the first hour of the published hyetograph ``TS1``); subcatchment 8,
which drains straight to the outfall, loads no conduit and is dropped.

`tree_kinwave_large.inp` -- a synthetic 32-conduit dendritic tree (seeded, below) with
diameters 0.15-1.05 m, slopes 0.002-0.03 and target fill ratios ``q / Qfull`` of 0.3-0.95, every
seventh pipe oversized (the generated file spans 8e-5 to 0.81), so every branch of SWMM's
circular section is exercised: ``getAcircular`` /
``getScircular`` near the invert (``S/Sfull <= 0.015``, ``A/Afull < 0.04``) and the
tabulated range up to near-full flow.
"""

from __future__ import annotations

import math
import random
from pathlib import Path

HERE = Path(__file__).resolve().parent
FT = 0.3048

OPTIONS = """[OPTIONS]
FLOW_UNITS           CMS
INFILTRATION         HORTON
FLOW_ROUTING         KINWAVE
LINK_OFFSETS         DEPTH
MIN_SLOPE            0
ALLOW_PONDING        NO
SKIP_STEADY_STATE    NO
START_DATE           01/01/2026
START_TIME           00:00:00
REPORT_START_DATE    01/01/2026
REPORT_START_TIME    00:00:00
END_DATE             01/01/2026
END_TIME             {end}
REPORT_STEP          00:05:00
WET_STEP             00:01:00
DRY_STEP             00:01:00
ROUTING_STEP         5
THREADS              1

[EVAPORATION]
CONSTANT         0.0
DRY_ONLY         NO
"""


def _write(path, title, junctions, outfalls, conduits, xsections, inflows, end="12:00:00"):
    lines = ["[TITLE]", title, "", OPTIONS.format(end=end), "[JUNCTIONS]"]
    lines += [f"{n:<8} {z:.6f} 10 0 0 0" for n, z in junctions]
    lines += ["", "[OUTFALLS]"]
    lines += [f"{n:<8} {z:.6f} FREE NO" for n, z in outfalls]
    lines += ["", "[CONDUITS]"]
    lines += [
        f"{c:<8} {a:<8} {b:<8} {length:.6f} {n} {o1:.6f} {o2:.6f} 0 0"
        for c, a, b, length, n, o1, o2 in conduits
    ]
    lines += ["", "[XSECTIONS]"]
    lines += [f"{c:<8} CIRCULAR {d:.6f} 0 0 0 1" for c, d in xsections]
    lines += ["", "[INFLOWS]"]
    lines += [f'{n:<8} FLOW "" FLOW 1.0 1.0 {q:.6g}' for n, q in inflows]
    lines += ["", "[REPORT]", "INPUT NO", "NODES ALL", "LINKS ALL", ""]
    path.write_text("\n".join(lines), newline="\n")


def example1():
    junctions = [(9, 1000), (10, 995), (13, 995), (14, 990), (15, 987), (16, 985),
                 (17, 980), (19, 1010), (20, 1005), (21, 990), (22, 987), (23, 990),
                 (24, 984)]
    conduits = [(1, 9, 10, 400, 0, 0), (4, 19, 20, 200, 0, 0), (5, 20, 21, 200, 0, 0),
                (6, 10, 21, 400, 0, 1), (7, 21, 22, 300, 1, 1), (8, 22, 16, 300, 0, 0),
                (10, 17, 18, 400, 0, 0), (11, 13, 14, 400, 0, 0), (12, 14, 15, 400, 0, 0),
                (13, 15, 16, 400, 0, 0), (14, 23, 24, 400, 0, 0), (15, 16, 24, 100, 0, 0),
                (16, 24, 17, 400, 0, 0)]
    diameters = {1: 1.5, 4: 1, 5: 1, 6: 1, 7: 2, 8: 2, 10: 2, 11: 1.5, 12: 1.5, 13: 1.5,
                 14: 1, 15: 2, 16: 2}
    # (outlet, area ac, %imperv) of subcatchments 1-7.
    subcatchments = [(9, 10, 50), (10, 10, 50), (13, 5, 50), (22, 5, 50), (15, 15, 50),
                     (23, 12, 10), (19, 4, 10)]
    intensity = 0.25 / 12.0 / 3600.0                    # in/hr -> ft/s
    inflows = [
        (str(node), (imperv / 100.0) * intensity * (area * 43560.0) * FT**3)
        for node, area, imperv in subcatchments
    ]
    _write(
        HERE / "example1_kinwave.inp",
        "EPA SWMM 5 Example1 conduit network in metres, rational-method constant inflows "
        "(C = %Imperv, i = 0.25 in/hr); generated by make_kinwave_fixtures.py",
        [(str(n), z * FT) for n, z in junctions],
        [("18", 975 * FT)],
        [(str(c), str(a), str(b), length * FT, 0.01, o1 * FT, o2 * FT)
         for c, a, b, length, o1, o2 in conduits],
        [(str(c), diameters[c] * FT) for c in diameters],
        inflows,
    )


def large_tree(seed=20260927, n_pipes=32):
    rng = random.Random(seed)
    sizes = [0.15, 0.225, 0.3, 0.375, 0.45, 0.6, 0.75, 0.9, 1.05]
    # parent[i] is the downstream node of junction i; junction 0 drains to the outfall.
    parent = {0: "OUT"}
    for i in range(1, n_pipes):
        parent[i] = rng.randrange(max(0, i - 6), i)
    children = {i: [j for j in parent if parent[j] == i] for i in parent}
    lateral = {}
    for i in parent:
        u = rng.random()
        # Spread the lateral inflows over five decades.
        lateral[i] = 10.0 ** (-5.0 + 4.0 * u) if not children[i] else 10.0 ** (-4 + 2 * u)

    def total(i):
        return lateral[i] + sum(total(j) for j in children[i])

    def q_full(d, n, s):
        a = math.pi / 4.0 * d * d
        return a * (d / 4.0) ** (2.0 / 3.0) * math.sqrt(s) / n

    fills = {}
    pipes = []
    for i in parent:
        q = total(i)
        s = rng.choice([0.002, 0.004, 0.006, 0.01, 0.015, 0.02, 0.03])
        n = rng.choice([0.011, 0.012, 0.013, 0.015])
        target = rng.uniform(0.3, 0.95)
        d = next((d for d in sizes if q / q_full(d, n, s) <= target), sizes[-1])
        if q / q_full(d, n, s) > 0.95:
            s = 0.03
        if i % 7 == 3:
            d = sizes[-1]                      # oversized: exercises the near-invert branch
        length = rng.choice([40.0, 60.0, 80.0, 100.0, 120.0, 150.0])
        fills[i] = q / q_full(d, n, s)
        pipes.append((i, d, n, s, length))
    elevation = {"OUT": 10.0}
    order = sorted(parent, key=lambda i: _depth(parent, i))
    geometry = {i: (d, n, s, length) for i, d, n, s, length in pipes}
    for i in order:
        d, n, s, length = geometry[i]
        down = elevation[parent[i]] if parent[i] == "OUT" else elevation[f"J{parent[i]}"]
        dy = s * length / math.sqrt(1.0 + s * s)
        elevation[f"J{i}"] = round(down + dy, 6)
    junctions = [(f"J{i}", elevation[f"J{i}"]) for i in sorted(parent)]
    conduits = [
        (f"C{i}", f"J{i}", "OUT" if parent[i] == "OUT" else f"J{parent[i]}", length, n, 0.0,
         0.0)
        for i, d, n, s, length in pipes
    ]
    _write(
        HERE / "tree_kinwave_large.inp",
        f"Synthetic {n_pipes}-conduit dendritic tree, seed {seed}, fills q/Qfull "
        f"{min(fills.values()):.1e}-{max(fills.values()):.2f}; generated by "
        f"make_kinwave_fixtures.py",
        junctions,
        [("OUT", 10.0)],
        conduits,
        [(f"C{i}", d) for i, d, *_ in pipes],
        [(f"J{i}", lateral[i]) for i in sorted(parent)],
    )


def _depth(parent, i):
    k = 0
    while parent[i] != "OUT":
        i = parent[i]
        k += 1
    return k


if __name__ == "__main__":
    example1()
    large_tree()
