"""SWMM parity on the committed tree, through pyswmm 2.1.0 / SWMM 5.2.4.

pyswmm ALWAYS writes a `.rpt` and a `.out` next to the model it runs (`pyswmm/swmm5.py`
silently derives both paths when they are not given), so every test here copies the fixture
into `tmp_path` and hands the engine explicit output paths there. Nothing is written into
the repository.
"""

import shutil
from pathlib import Path

import pytest
import torch

from noodl.apps.sewer.inp import read_swmm_inp
from noodl.apps.sewer.network import build_model, sewer_steady

pyswmm = pytest.importorskip("pyswmm")
shared_enum = pytest.importorskip("swmm.toolkit.shared_enum")

F64 = torch.float64
DATA = Path(__file__).resolve().parents[1] / "data" / "sewer"
LINKS = ["C1", "C2", "C3", "C4", "C5"]



#: The kinematic-wave parity networks: the hand-built 5-conduit tree, the conduit network of
#: EPA SWMM 5's published Example 1 (13 conduits, in metres, runoff replaced by rational-method
#: constant inflows), and a synthetic 32-conduit tree whose fills span 8e-5 to 0.81 of
#: ``Qfull`` so that SWMM's near-invert closed forms are exercised as well as its tables.
#: The last two are regenerated by `tests/data/sewer/make_kinwave_fixtures.py`.
NETWORKS = ["tree_kinwave.inp", "example1_kinwave.inp", "tree_kinwave_large.inp"]

#: Depth and volume come from the LIVE engine (`Link.depth`, `Link.volume` return SWMM's
#: float64 `newDepth` / `newVolume` times its unit factor), and `geometry="swmm"` performs
#: SWMM's own float64 operations (`swmm_xsect.py`) in essentially SWMM's order, so the only
#: admissible difference is float64 rounding: ~50 operations at unit roundoff 1.1e-16, through
#: a piecewise-linear inverse and a Newton root whose relative condition numbers are O(1),
#: bounds it near 1e-13. 1e-10 leaves three decades of headroom over that bound and is five
#: decades below the 1e-5-1e-3 table-versus-circle difference the check exists to exclude.
TOL_FLOAT64 = 1e-10

#: Velocity has no live accessor under KINWAVE (see `test_velocities`) and is read from the
#: BINARY output, which stores float32: its rounding is at most half an ulp, 2**-24 = 5.96e-8
#: relative. 1e-7 is that bound plus the float64 margin above.
TOL_FLOAT32 = 1e-7


def _run_swmm(tmp_path, name, links=None):
    """Run the fixture and return the live link results plus the binary velocities."""
    inp = tmp_path / name
    shutil.copy(DATA / name, inp)
    if links is None:
        links = [p.name for p in read_swmm_inp(inp)[0].pipes]
    out = {}
    with pyswmm.Simulation(
        str(inp), str(tmp_path / f"{inp.stem}.rpt"), str(tmp_path / f"{inp.stem}.out")
    ) as sim:
        for _ in sim:
            pass
        for link_id in links:
            link = pyswmm.Links(sim)[link_id]
            entry = {"flow": link.flow, "depth": link.depth, "volume": link.volume}
            try:
                entry["pollut"] = dict(link.pollut_quality)
            except Exception:  # pragma: no cover - only when no pollutant is defined
                entry["pollut"] = {}
            out[link_id] = entry
        out["error"] = sim.flow_routing_error
        out["engine"] = sim.engine_version
    with pyswmm.Output(str(tmp_path / f"{inp.stem}.out")) as binary:
        for link_id in links:
            series = binary.link_series(link_id, shared_enum.LinkAttribute.FLOW_VELOCITY)
            out[link_id]["velocity"] = list(series.items())[-1][1]
    return out


def _noodl(name, geometry="swmm"):
    net, _, _ = read_swmm_inp(DATA / name, geometry=geometry)
    model, state, drivers = build_model(net, air=False, quality=False)
    return net, model._apply_closures(state, drivers)


@pytest.fixture(scope="module", params=NETWORKS)
def parity(request, tmp_path_factory):
    """`(net, noodl resolved state, SWMM results)` per network, SWMM run once."""
    name = request.param
    net, resolved = _noodl(name)
    swmm = _run_swmm(tmp_path_factory.mktemp(name.split(".")[0]), name)
    return net, resolved, swmm


def _worst(net, resolved, swmm, key, attr):
    worst = 0.0
    for i, name in enumerate(p.name for p in net.pipes):
        mine, theirs = float(resolved[key][i]), swmm[name][attr]
        if theirs == 0.0:
            assert mine == 0.0, (name, attr, mine)
            continue
        worst = max(worst, abs(mine - theirs) / abs(theirs))
    return worst


def test_the_engine_is_the_one_the_measurements_used(parity):
    _, _, swmm = parity
    # `Simulation.engine_version` returns a `packaging.version.Version` (the docstring's own
    # `LooseVersion` type hint is stale), which compares unequal to a bare `str` under `==`
    # (`NotImplemented`, so pytest reports it as a plain inequality) -- `str()` it first.
    assert str(swmm["engine"]) == "5.2.4"
    assert swmm["error"] == 0.0


def test_pipe_flows(parity):
    """1e-9 relative: continuity alone, identical on both sides up to the steady state
    SWMM's time stepping reaches."""
    assert _worst(*parity, "sewer.q", "flow") < 1e-9


def test_normal_depths(parity):
    """`TOL_FLOAT64`. SWMM reports ``(Y(a1) + Y(a2)) / 2`` from its 51-point ``Y_Circ``
    table (Ref. Man. Vol. II section 5.1.3; `flowrout.c::setNewLinkState`), which
    `geometry="swmm"` reproduces (`noodl.apps.sewer.swmm_xsect`)."""
    assert _worst(*parity, "sewer.h", "depth") < TOL_FLOAT64


def test_velocities(parity):
    """`TOL_FLOAT32`, against the BINARY output's FLOW_VELOCITY.

    Under KINWAVE, `Link.ups_xsection_area` is exactly 0.0 (SWMM fills it only under
    DYNWAVE), so `flow / ups_xsection_area` is 0/0 and there is no live velocity. SWMM's
    velocity is ``q / A_Circ(depth)`` and exactly zero at a depth of 0.01 ft or less
    (`link.c::link_getVelocity`); both are reproduced.
    """
    assert _worst(*parity, "sewer.v", "velocity") < TOL_FLOAT32


def test_conduit_volumes(parity):
    """`TOL_FLOAT64`. The capacity every quality layer is built on: SWMM's
    ``(a1 + a2) / 2 * L`` in its reporting convention (1 ft3 = 0.02832 m3)."""
    assert _worst(*parity, "sewer.V_wet", "volume") < TOL_FLOAT64


def test_tracer_concentration(tmp_path):
    """1e-9 relative, the tank-in-series closed form against SWMM.

    The model's steady state IS the tank-in-series closed form: a manhole's balance is
    `sum(q_in C_in) = (q_out + k V) C`, which is exactly `C = C_mix / (1 + k tau)` with
    `tau = V / q`. SWMM's own conduit model reaches the same steady state EXACTLY, at any
    step: `qualrout.c::findLinkQual` applies `c (1 - k dt)` (`getReactedQual`) and then mixes
    with the inflow over the OLD volume, `c = (c V + c_in q dt) / (V + q dt)`
    (`getMixedQual`), whose fixed point is `c = c_in q / (q + k V)`. With
    `geometry="swmm"` the volume `V` is SWMM's own, so what remains is float64 rounding
    (~1e-15) and SWMM's distance from steady state after 2 h: the slowest tank has
    `tau = V/q < 170 s`, so three tanks in series have decayed by
    `(t/tau)^2/2 exp(-t/tau) < 1e-15` by t = 7200 s. 1e-9 is a wide margin over both.
    """
    from noodl.layers.reaction import FirstOrderDecay

    net, loads, pollutants = read_swmm_inp(DATA / "tree_kinwave_pollut.inp")
    model, state, drivers = build_model(net, air=False, quality=False)
    resolved = model._apply_closures(state, drivers)
    k = pollutants["Tracer"]["decay"]
    volume = resolved["sewer.V_wet"]
    q = resolved["sewer.q"]
    tau = volume / q
    order = {p.name: i for i, p in enumerate(net.pipes)}
    # The tree, resolved by hand: C1 and C2 mix at J3 into C3; C3 and C4 mix at J4 into C5.
    c = {}
    c["C1"] = 0.1 / (1.0 + k * float(tau[order["C1"]]))
    c["C2"] = 0.0
    c["C4"] = 0.0
    mix_j3 = (c["C1"] * 0.05 + c["C2"] * 0.08) / 0.13
    c["C3"] = mix_j3 / (1.0 + k * float(tau[order["C3"]]))
    mix_j4 = (c["C3"] * 0.13 + c["C4"] * 0.03) / 0.16
    c["C5"] = mix_j4 / (1.0 + k * float(tau[order["C5"]]))
    _ = FirstOrderDecay  # the framework reaction the app's own layer would carry
    swmm = _run_swmm(tmp_path, "tree_kinwave_pollut.inp")
    worst = 0.0
    for name in LINKS:
        theirs = swmm[name]["pollut"]["Tracer"] * 1e-3      # mg/L -> kg/m3
        mine = c[name]
        if mine == 0.0:
            assert abs(theirs) < 1e-12
            continue
        worst = max(worst, abs(mine - theirs) / mine)
    assert worst < 1e-9, worst




def _tracer_model(net, loads, pollutants):
    """`build_model(quality=True, air=False)` carrying the fixture's `Tracer` on the BOD column.

    `Tracer` is a plain first-order-decay pollutant with no sulfide-generation analogue, and
    `SulfideGeneration`'s own `k_bod` IS constructor-configurable, so the model's BOD decay is
    set to the fixture's own `Kdecay`, converted back from `read_swmm_inp`'s per-SECOND
    `pollutants[...]["decay"]` to the per-DAY units `k_bod` expects. `Model.reactions` is a
    plain list attribute, so this substitutes the reaction's PARAMETER only; the reaction's
    position in the step and the sampling point are the builder's own.
    `T_water` is set to 20 C (`theta = 1.07 ** (T - 20) == 1`) so the reaction's temperature
    correction (absent from SWMM's plain first-order decay) does not enter the comparison;
    it is tested on its own terms in
    `tests/apps/sewer/test_quality.py::test_sulfide_rate_against_the_closed_form`.
    """
    from noodl.apps.sewer.quality import SulfideGeneration

    model, state, drivers = build_model(net, air=False, quality=True)
    model.reactions = [(
        "water_quality",
        SulfideGeneration(
            out_pipe=model.out_pipe, manhole_idx=model.manhole_idx,
            n_nodes=model.net.n, k_bod=pollutants["Tracer"]["decay"] * 86400.0,
        ),
    )]
    drivers = dict(drivers)
    bod_in = torch.zeros(model.net.n, dtype=F64)
    for node, species in loads.items():
        bod_in[model.net.nodes.index(node)] = species["Tracer"]
    drivers["bod_in"] = bod_in
    drivers["T_water"] = torch.tensor(20.0, dtype=F64)
    return model, state, drivers


def _per_pipe(model, net, x):
    """The water_quality state (manhole order, BOD column) as `{pipe name: kg/m3}`: a
    manhole's concentration IS its outgoing conduit's."""
    pipe_to_manhole = {int(model.out_pipe[m]): m for m in range(len(model.out_pipe))}
    return {p.name: float(x[pipe_to_manhole[pos], 0]) for pos, p in enumerate(net.pipes)}


def test_tracer_model_run_through_the_lateral_load_path(tmp_path):
    """The test above never runs the model's quality layer at all -- it builds
    `quality=False` and resolves the tank-in-series closed form BY HAND. This test runs the
    app's own model (`quality=True, air=False`, the fixture's tracer load through the
    `LateralLoads`/`bod_in` path, see `_tracer_model`) to its fixed point with
    `sewer_steady`, and compares the state it RETURNS -- no reaction removed, no extra
    step -- against the SAME SWMM values.

    Same scheme, same sampling point. Both codes split each step into an explicit
    first-order decay `R: c -> c (1 - k dt)` and an implicit upwind mixing `T` over the
    conduit volume (`qualrout.c::findLinkQual`: `getReactedQual`, then `getMixedQual`), and
    report the concentration after `T`: `build_model` sets
    `Model(reaction_order="before_transport")`. The fixed point of `T(R(x))` satisfies
    `x (q + k V) = sum(q_u x_u) + load` at any dt, the closed form above, which is also
    SWMM's. (Sampled after `R` instead, the model's fixed point would be `(1 - k dt)` times
    SWMM's, 3.47e-3 relative at dt = 60 s.)

    1e-9 relative, as above: `sewer_steady` stops when no concentration changes by more than
    1e-14 kg/m3 in a step (1e-13 relative on the 0.1 kg/m3 load), and with `dt / tau > 0.35`
    per tank the remaining distance to the fixed point is at most a few times that.
    """
    net, loads, pollutants = read_swmm_inp(DATA / "tree_kinwave_pollut.inp")
    model, state, drivers = _tracer_model(net, loads, pollutants)
    final = sewer_steady(model, state, drivers, dt=60.0, max_iter=100_000, tol=1e-14)
    mine = _per_pipe(model, net, final["water_quality.x"])

    swmm = _run_swmm(tmp_path, "tree_kinwave_pollut.inp")
    worst = 0.0
    for name in LINKS:
        theirs = swmm[name]["pollut"]["Tracer"] * 1e-3
        if theirs == 0.0:
            assert abs(mine[name]) < 1e-12
            continue
        worst = max(worst, abs(mine[name] - theirs) / theirs)
    assert worst < 1e-9, worst


#: The transient variant of `tree_kinwave_pollut.inp`, written into `tmp_path` only: the
#: `J1` tracer concentration follows a time series (zero for the first hour, while SWMM's
#: kinematic-wave hydraulics spin up to the steady flows, then a ramp to 100 mg/L, a
#: plateau and a ramp back down), and the run ends at 01:40.
_TRANSIENT_EDITS = (
    (
        'J1               Tracer           ""               CONCENTRATION   1.0      1.0'
        "      100.0",
        "J1               Tracer           TRC              CONCENTRATION   1.0      1.0"
        "      0.0",
    ),
    ("END_TIME             02:00:00", "END_TIME             01:40:00"),
    (
        "[REPORT]",
        "[TIMESERIES]\n"
        "TRC  01/01/2026 01:00 0.0\n"
        "TRC  01/01/2026 01:10 100.0\n"
        "TRC  01/01/2026 01:20 100.0\n"
        "TRC  01/01/2026 01:25 0.0\n"
        "TRC  01/01/2026 02:00 0.0\n\n"
        "[REPORT]",
    ),
)


def test_tracer_transient_at_every_step(tmp_path):
    """Time-varying tracer load, compared at EVERY 5 s routing step of SWMM.

    SWMM's live step loop (`pyswmm.Simulation` iterates one routing step at a time) is
    sampled after each step: the link concentrations, and the `J1` node concentration,
    which for a node fed by nothing but its lateral inflow IS the inflow concentration SWMM
    applied over that step. The model is driven with that same value per step (`bod_in` at
    `J1`), so the time at which SWMM evaluates its time series (the step start, to within
    its own datetime rounding) does not enter the comparison.

    What is compared, and why:

    * `C1`, the conduit fed only by `J1`'s lateral inflow: SWMM's step is
      `c' = (c (1 - k dt) V1 + c_in q dt) / (V1 + q dt)`, and the model's R-then-implicit-T
      step at the steady storage (`V1 = V2 = V`, `q_in = q_out = q`) is the same
      expression, so the returned state must equal SWMM's sample at every step: 1e-9
      relative, as for the steady tests (measured 1.1e-14).
    * `C3`, `C5`, the conduits fed by upstream conduits: SWMM's junction mixing
      (`findLinkMassFlow`) uses the upstream links' START-of-step concentrations
      (`Link.oldQual`), an explicit one-step lag per junction, where the model's transport
      solve is implicit over the whole tree. That difference is first order in dt and is not
      a sampling-point question: as a fraction of each conduit's peak it measures 1.08e-2
      (C3) and 1.75e-2 (C5) at dt = 5 s, and 2.2e-3 and 3.5e-3 at dt = 1 s. What IS
      asserted for them, at 1e-9 relative, is that SWMM equals exactly that lagged
      recursion built on the model's own `V` and `q` (measured 5e-15), so the lag is the
      whole of the difference.
    * `C2`, `C4` carry no load and stay exactly zero in both codes.

    Transient HYDRAULICS are not compared here and cannot be: the model's water side is
    quasi-steady (or manhole storage under `storage=True`), not SWMM's kinematic wave, so
    under a time-varying FLOW the storages differ before any quality question arises. For
    the record, SWMM mixes over the step-start volume, `(c V1 + c_in q_in dt) / (V1 +
    q_in dt)`, where the model's amount form is `(c V1 + c_in q_in dt) / (V2 + q_out dt)`;
    the two denominators agree exactly when `V2 - V1 = (q_in - q_out) dt`.
    """
    text = (DATA / "tree_kinwave_pollut.inp").read_text()
    for old, new in _TRANSIENT_EDITS:
        assert text.count(old) == 1, old
        text = text.replace(old, new)
    inp = tmp_path / "tree_kinwave_pollut_transient.inp"
    inp.write_text(text)
    samples = []
    with pyswmm.Simulation(
        str(inp), str(tmp_path / f"{inp.stem}.rpt"), str(tmp_path / f"{inp.stem}.out")
    ) as sim:
        links, nodes = pyswmm.Links(sim), pyswmm.Nodes(sim)
        for _ in sim:
            samples.append((
                (sim.current_time - sim.start_time).total_seconds(),
                nodes["J1"].pollut_quality["Tracer"] * 1e-3,
                {name: links[name].pollut_quality["Tracer"] * 1e-3 for name in LINKS},
            ))

    net, loads, pollutants = read_swmm_inp(DATA / "tree_kinwave_pollut.inp")
    model, state, drivers = _tracer_model(net, loads, pollutants)
    k = pollutants["Tracer"]["decay"]
    resolved = model._apply_closures(state, drivers)
    order = {p.name: i for i, p in enumerate(net.pipes)}
    volume = {name: float(resolved["sewer.V_wet"][order[name]]) for name in LINKS}
    q = {name: float(resolved["sewer.q"][order[name]]) for name in LINKS}
    upstream = {"C3": ("C1", "C2"), "C5": ("C3", "C4")}
    j1 = model.net.nodes.index("J1")

    current, lagged, t_prev = state, dict.fromkeys(LINKS, 0.0), 0.0
    worst_c1 = worst_lag = 0.0
    loaded = 0
    for t, c_j1, theirs in samples:
        dt = t - t_prev
        t_prev = t
        bod_in = torch.zeros(model.net.n, dtype=F64)
        bod_in[j1] = c_j1
        current = model.step(current, {**drivers, "bod_in": bod_in}, dt)
        mine = _per_pipe(model, net, current["water_quality.x"])
        # SWMM's own recursion (qualrout.c), upstream links at their step-START values.
        c_in = {"C1": c_j1, "C2": 0.0, "C4": 0.0}
        for name, ups in upstream.items():
            c_in[name] = sum(q[u] * lagged[u] for u in ups) / q[name]
        lagged = {
            name: (lagged[name] * (1.0 - k * dt) * volume[name] + c_in[name] * q[name] * dt)
            / (volume[name] + q[name] * dt)
            for name in LINKS
        }
        for name in ("C2", "C4"):
            assert mine[name] == 0.0 and theirs[name] == 0.0
        if theirs["C1"] != 0.0:
            loaded += 1
            worst_c1 = max(worst_c1, abs(mine["C1"] - theirs["C1"]) / theirs["C1"])
        else:
            assert mine["C1"] == 0.0
        for name in upstream:
            if theirs[name] == 0.0:
                assert lagged[name] == 0.0
                continue
            worst_lag = max(worst_lag, abs(lagged[name] - theirs[name]) / theirs[name])
    # Every 5 s routing step up to the end of the run (pyswmm yields all but the last).
    assert [t for t, _, _ in samples] == [5.0 * (i + 1) for i in range(1199)]
    assert loaded > 400                             # the load pulse was really seen
    assert worst_c1 < 1e-9, worst_c1
    assert worst_lag < 1e-9, worst_lag
