"""SWMM parity on the committed tree, through pyswmm 2.1.0 / SWMM 5.2.4.

pyswmm ALWAYS writes a `.rpt` and a `.out` next to the model it runs (`pyswmm/swmm5.py`
silently derives both paths when they are not given), so every test here copies the fixture
into `tmp_path` and hands the engine explicit output paths there. Nothing is written into
the repository.
"""

import shutil
from pathlib import Path

import pytest
import torch

from noodl.apps.sewer.inp import read_swmm_inp
from noodl.apps.sewer.network import build_model, sewer_steady

pyswmm = pytest.importorskip("pyswmm")
shared_enum = pytest.importorskip("swmm.toolkit.shared_enum")

F64 = torch.float64
DATA = Path(__file__).resolve().parents[1] / "data" / "sewer"
LINKS = ["C1", "C2", "C3", "C4", "C5"]



#: The kinematic-wave parity networks: the hand-built 5-conduit tree, the conduit network of
#: EPA SWMM 5's published Example 1 (13 conduits, in metres, runoff replaced by rational-method
#: constant inflows), and a synthetic 32-conduit tree whose fills span 8e-5 to 0.81 of
#: ``Qfull`` so that SWMM's near-invert closed forms are exercised as well as its tables.
#: The last two are regenerated by `tests/data/sewer/make_kinwave_fixtures.py`.
NETWORKS = ["tree_kinwave.inp", "example1_kinwave.inp", "tree_kinwave_large.inp"]

#: Depth and volume come from the LIVE engine (`Link.depth`, `Link.volume` return SWMM's
#: float64 `newDepth` / `newVolume` times its unit factor), and `geometry="swmm"` performs
#: SWMM's own float64 operations (`swmm_xsect.py`) in essentially SWMM's order, so the only
#: admissible difference is float64 rounding: ~50 operations at unit roundoff 1.1e-16, through
#: a piecewise-linear inverse and a Newton root whose relative condition numbers are O(1),
#: bounds it near 1e-13. 1e-10 leaves three decades of headroom over that bound and is five
#: decades below the 1e-5-1e-3 table-versus-circle difference the check exists to exclude.
TOL_FLOAT64 = 1e-10

#: Velocity has no live accessor under KINWAVE (see `test_velocities`) and is read from the
#: BINARY output, which stores float32: its rounding is at most half an ulp, 2**-24 = 5.96e-8
#: relative. 1e-7 is that bound plus the float64 margin above.
TOL_FLOAT32 = 1e-7


def _run_swmm(tmp_path, name, links=None):
    """Run the fixture and return the live link results plus the binary velocities."""
    inp = tmp_path / name
    shutil.copy(DATA / name, inp)
    if links is None:
        links = [p.name for p in read_swmm_inp(inp)[0].pipes]
    out = {}
    with pyswmm.Simulation(
        str(inp), str(tmp_path / f"{inp.stem}.rpt"), str(tmp_path / f"{inp.stem}.out")
    ) as sim:
        for _ in sim:
            pass
        for link_id in links:
            link = pyswmm.Links(sim)[link_id]
            entry = {"flow": link.flow, "depth": link.depth, "volume": link.volume}
            try:
                entry["pollut"] = dict(link.pollut_quality)
            except Exception:  # pragma: no cover - only when no pollutant is defined
                entry["pollut"] = {}
            out[link_id] = entry
        out["error"] = sim.flow_routing_error
        out["engine"] = sim.engine_version
    with pyswmm.Output(str(tmp_path / f"{inp.stem}.out")) as binary:
        for link_id in links:
            series = binary.link_series(link_id, shared_enum.LinkAttribute.FLOW_VELOCITY)
            out[link_id]["velocity"] = list(series.items())[-1][1]
    return out


def _noodl(name, geometry="swmm"):
    net, _, _ = read_swmm_inp(DATA / name, geometry=geometry)
    model, state, drivers = build_model(net, air=False, quality=False)
    return net, model._apply_closures(state, drivers)


@pytest.fixture(scope="module", params=NETWORKS)
def parity(request, tmp_path_factory):
    """`(net, noodl resolved state, SWMM results)` per network, SWMM run once."""
    name = request.param
    net, resolved = _noodl(name)
    swmm = _run_swmm(tmp_path_factory.mktemp(name.split(".")[0]), name)
    return net, resolved, swmm


def _worst(net, resolved, swmm, key, attr):
    worst = 0.0
    for i, name in enumerate(p.name for p in net.pipes):
        mine, theirs = float(resolved[key][i]), swmm[name][attr]
        if theirs == 0.0:
            assert mine == 0.0, (name, attr, mine)
            continue
        worst = max(worst, abs(mine - theirs) / abs(theirs))
    return worst


def test_the_engine_is_the_one_the_measurements_used(parity):
    _, _, swmm = parity
    # `Simulation.engine_version` returns a `packaging.version.Version` (the docstring's own
    # `LooseVersion` type hint is stale), which compares unequal to a bare `str` under `==`
    # (`NotImplemented`, so pytest reports it as a plain inequality) -- `str()` it first.
    assert str(swmm["engine"]) == "5.2.4"
    assert swmm["error"] == 0.0


def test_pipe_flows(parity):
    """1e-9 relative: continuity alone, identical on both sides up to the steady state
    SWMM's time stepping reaches."""
    assert _worst(*parity, "sewer.q", "flow") < 1e-9


def test_normal_depths(parity):
    """`TOL_FLOAT64`. SWMM reports ``(Y(a1) + Y(a2)) / 2`` from its 51-point ``Y_Circ``
    table (Ref. Man. Vol. II section 5.1.3; `flowrout.c::setNewLinkState`), which
    `geometry="swmm"` reproduces (`noodl.apps.sewer.swmm_xsect`)."""
    assert _worst(*parity, "sewer.h", "depth") < TOL_FLOAT64


def test_velocities(parity):
    """`TOL_FLOAT32`, against the BINARY output's FLOW_VELOCITY.

    Under KINWAVE, `Link.ups_xsection_area` is exactly 0.0 (SWMM fills it only under
    DYNWAVE), so `flow / ups_xsection_area` is 0/0 and there is no live velocity. SWMM's
    velocity is ``q / A_Circ(depth)`` and exactly zero at a depth of 0.01 ft or less
    (`link.c::link_getVelocity`); both are reproduced.
    """
    assert _worst(*parity, "sewer.v", "velocity") < TOL_FLOAT32


def test_conduit_volumes(parity):
    """`TOL_FLOAT64`. The capacity every quality layer is built on: SWMM's
    ``(a1 + a2) / 2 * L`` in its reporting convention (1 ft3 = 0.02832 m3)."""
    assert _worst(*parity, "sewer.V_wet", "volume") < TOL_FLOAT64


def test_tracer_concentration(tmp_path):
    """1e-9 relative, the tank-in-series closed form against SWMM.

    The model's steady state IS the tank-in-series closed form: a manhole's balance is
    `sum(q_in C_in) = (q_out + k V) C`, which is exactly `C = C_mix / (1 + k tau)` with
    `tau = V / q`. SWMM's own conduit model reaches the same steady state EXACTLY, at any
    step: `qualrout.c::findLinkQual` applies `c (1 - k dt)` (`getReactedQual`) and then mixes
    with the inflow over the OLD volume, `c = (c V + c_in q dt) / (V + q dt)`
    (`getMixedQual`), whose fixed point is `c = c_in q / (q + k V)`. With
    `geometry="swmm"` the volume `V` is SWMM's own, so what remains is float64 rounding
    (~1e-15) and SWMM's distance from steady state after 2 h: the slowest tank has
    `tau = V/q < 170 s`, so three tanks in series have decayed by
    `(t/tau)^2/2 exp(-t/tau) < 1e-15` by t = 7200 s. 1e-9 is a wide margin over both.
    """
    from noodl.layers.reaction import FirstOrderDecay

    net, loads, pollutants = read_swmm_inp(DATA / "tree_kinwave_pollut.inp")
    model, state, drivers = build_model(net, air=False, quality=False)
    resolved = model._apply_closures(state, drivers)
    k = pollutants["Tracer"]["decay"]
    volume = resolved["sewer.V_wet"]
    q = resolved["sewer.q"]
    tau = volume / q
    order = {p.name: i for i, p in enumerate(net.pipes)}
    # The tree, resolved by hand: C1 and C2 mix at J3 into C3; C3 and C4 mix at J4 into C5.
    c = {}
    c["C1"] = 0.1 / (1.0 + k * float(tau[order["C1"]]))
    c["C2"] = 0.0
    c["C4"] = 0.0
    mix_j3 = (c["C1"] * 0.05 + c["C2"] * 0.08) / 0.13
    c["C3"] = mix_j3 / (1.0 + k * float(tau[order["C3"]]))
    mix_j4 = (c["C3"] * 0.13 + c["C4"] * 0.03) / 0.16
    c["C5"] = mix_j4 / (1.0 + k * float(tau[order["C5"]]))
    _ = FirstOrderDecay  # the framework reaction the app's own layer would carry
    swmm = _run_swmm(tmp_path, "tree_kinwave_pollut.inp")
    worst = 0.0
    for name in LINKS:
        theirs = swmm[name]["pollut"]["Tracer"] * 1e-3      # mg/L -> kg/m3
        mine = c[name]
        if mine == 0.0:
            assert abs(theirs) < 1e-12
            continue
        worst = max(worst, abs(mine - theirs) / mine)
    assert worst < 1e-9, worst


def test_tracer_model_run_through_the_lateral_load_path(tmp_path):
    """The test above never runs the model's quality layer at all -- it builds
    `quality=False` and resolves the tank-in-series closed form BY HAND. This test builds
    `quality=True, air=False`, feeds the fixture's own tracer load through the
    `LateralLoads`/`bod_in` path (mapping the tracer onto the BOD column: `Tracer` is a
    plain first-order-decay pollutant with no sulfide-generation analogue, and
    `SulfideGeneration`'s own `k_bod` IS constructor-configurable, so the model's BOD decay
    is set to the fixture's own `Kdecay`, converted back from `read_swmm_inp`'s per-SECOND
    `pollutants[...]["decay"]` to the per-DAY units `k_bod` expects), runs `sewer_steady`,
    and compares against the SAME SWMM values the hand-resolved closed form above used.

    `T_water` is set to 20 C (`theta = 1.07 ** (T - 20) == 1`) so the reaction's temperature
    correction (absent from SWMM's own plain first-order decay) does not contaminate the
    comparison; `T_water`'s temperature-dependence is tested on its own terms elsewhere
    (`tests/apps/sewer/test_quality.py::test_sulfide_rate_against_the_closed_form`).

    Same scheme, different sampling point. Both codes split each step into an explicit
    first-order decay `R: c -> c (1 - k dt)` and an implicit upwind mixing `T` over the
    conduit volume (`qualrout.c::findLinkQual`: `getReactedQual`, then `getMixedQual`;
    `Model.step`: the transport layer's implicit step, then `SulfideGeneration.apply`).
    The step sequences are the same, `... R T R T ...`, but SWMM reports the concentration
    after `T` and `Model.step` returns it after `R`, so the model's fixed point `x*` is
    `(1 - k dt)` times SWMM's (3.47e-3 relative at dt = 60 s, which the previous version of
    this test removed by Richardson extrapolation). Sampling the model after `T` instead --
    one TRANSPORT-ONLY step from `x*`, `T(x*)` -- is exactly SWMM's sample, at any dt: its
    fixed point satisfies `y (q + k V) = sum(q_u y_u) + load`, the closed form above.

    1e-9 relative, as above: `sewer_steady` stops when no concentration changes by more than
    1e-14 kg/m3 in a step (1e-13 relative on the 0.1 kg/m3 load), and with `dt / tau > 0.35`
    per tank the remaining distance to the fixed point is at most a few times that.
    """
    net, loads, pollutants = read_swmm_inp(DATA / "tree_kinwave_pollut.inp")
    k_per_second = pollutants["Tracer"]["decay"]
    dt = 60.0

    from noodl.apps.sewer.quality import SulfideGeneration

    model, state, drivers = build_model(net, air=False, quality=True)
    # Replace the builder's default-parameter reaction with one carrying the fixture's own
    # decay constant -- `Model.reactions` is a plain list attribute, not reconstructed
    # machinery, so this is a supported one-line substitution rather than a
    # private-internals hack.
    model.reactions = [(
        "water_quality",
        SulfideGeneration(
            out_pipe=model.out_pipe, manhole_idx=model.manhole_idx,
            n_nodes=model.net.n, k_bod=k_per_second * 86400.0,
        ),
    )]
    drivers = dict(drivers)
    bod_in = torch.zeros(model.net.n, dtype=F64)
    for node, species in loads.items():
        bod_in[model.net.nodes.index(node)] = species["Tracer"]
    drivers["bod_in"] = bod_in
    drivers["T_water"] = torch.tensor(20.0, dtype=F64)
    final = sewer_steady(model, state, drivers, dt=dt, max_iter=100_000, tol=1e-14)
    model.reactions = []
    sampled = model.step(final, drivers, dt)["water_quality.x"]
    pipe_to_manhole = {int(model.out_pipe[m]): m for m in range(len(model.out_pipe))}
    mine = {p.name: float(sampled[pipe_to_manhole[pos], 0]) for pos, p in enumerate(net.pipes)}

    swmm = _run_swmm(tmp_path, "tree_kinwave_pollut.inp")
    worst = 0.0
    for name in LINKS:
        theirs = swmm[name]["pollut"]["Tracer"] * 1e-3
        if theirs == 0.0:
            assert abs(mine[name]) < 1e-12
            continue
        worst = max(worst, abs(mine[name] - theirs) / theirs)
    assert worst < 1e-9, worst
