"""The IMPAQ port against the AQ_DT prototype — spec section 6.4.

The prototype lives outside this repository, so the byte-for-byte comparison is guarded
and the numbers it produces are ALSO stored in `tests/golden/impaq_test_network.json`,
which carries the check when the repository is absent.
"""

from __future__ import annotations

import math
import os
import sys
from pathlib import Path

import numpy as np
import pytest

from tellegen.apps.street.impaq import (
    build_test_network,
    canyon_velocity,
    compute_boundary_layer,
    compute_intersection_routing,
    flow_route,
    network_from_street_network,
    solve_steady_state,
)
from tellegen.apps.street.network import from_test_network
from tests.golden import load_golden

AQDT_ROOT = Path(os.environ.get("TELLEGEN_AQDT_ROOT",
                                r"<workspace>\tmp\2026_AQ_DT"))


def _prototype():
    """The AQ_DT prototype module, or a skip. Never modifies anything in that tree."""
    if not (AQDT_ROOT / "aqdt" / "impaq.py").exists():
        pytest.skip(f"the AQ_DT prototype is not at {AQDT_ROOT}")
    if str(AQDT_ROOT) not in sys.path:
        sys.path.insert(0, str(AQDT_ROOT))
    return pytest.importorskip("aqdt.impaq")


def _case():
    network = build_test_network()
    layer = compute_boundary_layer(network, 1e-4, 2.0, 0.25 * math.pi)
    network.roads.canyon_velocity_mps = canyon_velocity(
        network.roads, layer.friction_velocity_mps, layer.wind_angle_rad
    )
    return network, layer


def test_the_port_reproduces_the_prototype_exactly():
    prototype = _prototype()
    theirs = prototype.build_test_network()
    their_layer = prototype.compute_boundary_layer(theirs, 1e-4, 2.0, 0.25 * math.pi)
    theirs.roads.canyon_velocity_mps = prototype.canyon_velocity(
        theirs.roads, their_layer.friction_velocity_mps, their_layer.wind_angle_rad
    )
    ours, our_layer = _case()
    for attribute in ("length_m", "road_angle_rad", "center_x", "center_y",
                      "canyon_velocity_mps"):
        np.testing.assert_allclose(
            getattr(ours.roads, attribute), getattr(theirs.roads, attribute),
            rtol=1e-12, atol=0,
        )
    assert our_layer.friction_velocity_mps == their_layer.friction_velocity_mps
    _topology, their_routing = prototype.compute_intersection_routing(theirs)
    _topology, our_routing = compute_intersection_routing(ours)
    np.testing.assert_allclose(our_routing, their_routing, rtol=1e-12, atol=0)
    np.testing.assert_allclose(
        solve_steady_state(ours, our_layer),
        prototype.solve_steady_state(theirs, their_layer), rtol=1e-12, atol=0,
    )


def test_the_port_reproduces_the_stored_prototype_answer():
    """The same check, without the AQ_DT repository: the golden holds the prototype's own
    numbers, generated by `python -m benchmarks.regenerate_golden` while it was present."""
    network, layer = _case()
    golden = load_golden("impaq_test_network")
    np.testing.assert_allclose(network.roads.canyon_velocity_mps,
                               np.array(golden["canyon_velocity_mps"]),
                               rtol=1e-12, atol=0)
    assert abs(layer.friction_velocity_mps / golden["friction_velocity_mps"] - 1) < 1e-12
    for key, (fix_a, fix_b) in (("prototype", (False, False)),
                                ("fix_ab", (True, True))):
        np.testing.assert_allclose(
            solve_steady_state(network, layer, fix_a=fix_a, fix_b=fix_b),
            np.array(golden[key]), rtol=1e-12, atol=0,
        )


def test_each_fix_changes_the_answer_by_the_amount_recorded_in_the_plan():
    network, layer = _case()
    base = solve_steady_state(network, layer)
    both = solve_steady_state(network, layer, fix_a=True, fix_b=True)
    # Issue A is worth about 37 % on this network.
    assert 0.3 < float(np.max(np.abs(both - base) / np.abs(base))) < 0.45
    # The environment row is the background, whichever fixes are on.
    for solution in (base, both):
        assert abs(float(solution[-1]) - 1e-4) < 1e-15
    # Issue B alone is refused: four intersections against three roads would put
    # intersection 3 on the environment's own row.
    with pytest.raises(ValueError, match=r"fix_b without fix_a is only defined"):
        solve_steady_state(network, layer, fix_b=True)


def test_the_unfixed_state_is_oversized_and_the_fixed_one_is_not():
    from tellegen.apps.street.impaq import build_transport_system

    network, layer = _case()
    # Four intersections and three roads, so the prototype allocates five states where
    # four are wanted: issue B, verbatim.
    transport, _a, _b, _types = build_transport_system(network, layer)
    assert transport.shape[0] == 5
    # `fix_b` is only meaningful with `fix_a`, which makes the rows ROADS rather than
    # intersections; then four states is exactly right.
    transport, _a, _b, _types = build_transport_system(network, layer, fix_a=True,
                                                       fix_b=True)
    assert transport.shape[0] == 4


def test_flow_route_balances_a_simple_node():
    routing = flow_route(np.array([1.0, 1.0, -0.5, -0.5]),
                         np.array([0.0, 0.5 * math.pi, math.pi, 1.5 * math.pi]))
    assert routing.shape == (5, 5)
    assert bool((routing >= 0).all())
    assert abs(float(np.sum(routing[0, :])) - 1.0) < 1e-9
    assert abs(float(np.sum(routing[:, 2])) - 0.5) < 1e-9


def test_network_from_street_network_keeps_the_street_order_and_geometry():
    street_net = from_test_network()
    emission = np.array([1.0, 2.0, 3.0])
    converted = network_from_street_network(street_net, emission)
    reference = build_test_network()
    np.testing.assert_allclose(converted.roads.length_m, reference.roads.length_m,
                               rtol=1e-12, atol=0)
    np.testing.assert_allclose(converted.roads.road_angle_rad,
                               reference.roads.road_angle_rad, rtol=1e-12, atol=0)
    np.testing.assert_allclose(converted.roads.width_m, reference.roads.width_m)
    np.testing.assert_allclose(converted.roads.height_m, reference.roads.height_m)
    np.testing.assert_allclose(converted.roads.roughness_m, reference.roads.roughness_m)
    np.testing.assert_allclose(converted.roads.emission_rate, emission)
