"""The street application: a SIRANE/MUNICH-type street-network dispersion model.

A model built ON TOP of the core package. The core supplies
every solve; this package decides the network, the closures and the units. Nothing under
`src/noodl/` outside `apps/` imports from here.
"""

from noodl.apps.street_aq.above_roof import street_steady_with_plume
from noodl.apps.street_aq.canyon import (
    GAMMA_E,
    KAPPA,
    KAPPA_MUNICH,
    SCHULTE_BETA,
    SIRANE_EXCHANGE,
    Z0_B_DEFAULT,
    Z0_S_DEFAULT,
    BoundaryLayer,
    boundary_layer,
    canyon_velocity,
    exchange_velocity,
    macdonald_profile,
    roof_wind,
    soulhac_shape,
)
from noodl.apps.street_aq.case import (
    StreetCase,
    StreetResults,
    drivers_at,
    read_case,
    read_results,
    write_case,
    write_sweep,
)
from noodl.apps.street_aq.chemistry import (
    j_no2_elevation_cloud,
    j_no2_sirane,
    j_no2_zenith_table,
    k_no_o3_jpl2003,
    k_no_o3_sirane,
    k_no_o3_soulhac2011,
    photostationary_for_streets,
    solar_elevation,
    street_steady,
)
from noodl.apps.street_aq.closures import OPTIONS, PRESETS
from noodl.apps.street_aq.exposure import (
    Q_INHALATION,
    exposure_reduction_adjoint,
    exposure_reduction_forward,
    street_population,
    total_exposure,
)
from noodl.apps.street_aq.network import (
    Street,
    StreetNetwork,
    build_model,
    from_test_network,
    initial_state,
    munich_idealised,
    street_geometry,
    street_index,
)
from noodl.apps.street_aq.plume import (
    SEUIL_GAUSS,
    PlumeTable,
    StreetSources,
    downwind_cutoff,
    junction_kernel,
    junction_sources,
    plume_kernel,
    plume_table,
    source_points,
    street_kernel,
)
from noodl.apps.street_aq.report import (
    from_ug_m3,
    to_ug_m3,
    write_network_concentration,
)
from noodl.apps.street_aq.routing import (
    StreetFlows,
    StreetGeometry,
    direction_offsets,
    n_theta_munich,
    node_closure,
    routing_matrix,
    sigma_theta_munich,
    sirane_direction_samples,
)

__all__ = [
    "GAMMA_E",
    "KAPPA",
    "KAPPA_MUNICH",
    "OPTIONS",
    "PRESETS",
    "Q_INHALATION",
    "SCHULTE_BETA",
    "SEUIL_GAUSS",
    "SIRANE_EXCHANGE",
    "Z0_B_DEFAULT",
    "Z0_S_DEFAULT",
    "BoundaryLayer",
    "PlumeTable",
    "Street",
    "StreetCase",
    "StreetFlows",
    "StreetResults",
    "StreetSources",
    "StreetGeometry",
    "StreetNetwork",
    "boundary_layer",
    "build_model",
    "canyon_velocity",
    "direction_offsets",
    "downwind_cutoff",
    "drivers_at",
    "exchange_velocity",
    "exposure_reduction_adjoint",
    "exposure_reduction_forward",
    "from_test_network",
    "from_ug_m3",
    "initial_state",
    "j_no2_elevation_cloud",
    "j_no2_sirane",
    "j_no2_zenith_table",
    "junction_kernel",
    "junction_sources",
    "k_no_o3_jpl2003",
    "k_no_o3_sirane",
    "k_no_o3_soulhac2011",
    "macdonald_profile",
    "munich_idealised",
    "n_theta_munich",
    "node_closure",
    "photostationary_for_streets",
    "plume_kernel",
    "plume_table",
    "read_case",
    "read_results",
    "roof_wind",
    "routing_matrix",
    "sigma_theta_munich",
    "sirane_direction_samples",
    "solar_elevation",
    "source_points",
    "soulhac_shape",
    "street_geometry",
    "street_index",
    "street_kernel",
    "street_population",
    "street_steady",
    "street_steady_with_plume",
    "to_ug_m3",
    "total_exposure",
    "write_case",
    "write_network_concentration",
    "write_sweep",
]
